# ============================================================
# application-local.properties
# ⚠️ Este archivo NO va al repositorio (.gitignore)
# ============================================================

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/soundrecords
spring.datasource.username=postgres
spring.datasource.password=ayuda1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=soundrecords_secret_key_super_segura_2026
jwt.expiration=86400000

# Spotify
spotify.client-id=3adc4b9723af4ff4a3c1feb31eabd37b
spotify.client-secret=7289d8ee4f254440b5b2e7ffcaa69dab
spotify.redirect-uri=http://127.0.0.1:8080/api/spotify/callback

# Puerto del servidor
server.port=8080